version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    image: "docker-python-sandbox-supervisor-worker:latest"
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: "docker-python-sandbox-supervisor-development:latest"
    depends_on:
      - rabbitmq
      - worker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
